use_frameworks!

target 'HXCategoriesPro_Example' do
  platform :ios, '11.0'
  pod 'HXCategoriesPro', :path => '../'
end

target 'macApp' do
  platform :osx, '10.13'
  pod 'HXCategoriesPro', :path => '../'
end
