use_frameworks!

platform :ios, '9.0'

target 'HXGategories_Example' do
  pod 'HXGategories', :path => '../'

  target 'HXGategories_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
